# Generated by Django 3.0.8 on 2020-07-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='N/a', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(max_length=4000),
        ),
    ]
